<?php

/**
* Implement hook_menu().
*/
function sections_menu() {
  $items ['sections'] = array(
    'title' => 'All sections',
    'page callback' => 'all_sections_page',
    'access arguments' => array('access content'),
    );

  return $items;
};

/**
* hook_theme()
*/
function sections_theme() {
  return array(
    'all_sections' => array(
      'template' => 'all-sections',
      ),
  );
}

/**
* All sections callback
*/
function all_sections_page() {

  drupal_add_library('angularjs', 'angularjs');
  drupal_add_library('angularjs', 'angularjs');
  $path = drupal_get_path('module', 'sections');
  drupal_add_js($path . '/js/sections.gen.js');

  return theme('all_sections');
}
